columns:
  - Temperature
  - Humidity
  - Wind_Speed
  - Cloud_Cover
  - Pressure
  - Rain

numerical_columns:
  - Temperature
  - Humidity
  - Wind_Speed
  - Cloud_Cover
  - Pressure

categorical_columns:
  - Rain

target_column: Rain